### ISSUE TITLE
How to prefetch large batch of images?

### ISSUE THREAD

**Issue by sladkoff** [kfiroo/react-native-cached-image#36]
Hello, I've got a question.

I need to prefetch and cache hundreds of photos from an API to implement an offline-mode for an app. The total file size may exceed 1GB.

When I tried to download the images using the `cacheMultipleImages` function it crashed the app due to out of memory errors. 

Is it possible to use this component for such a usecase? 
Do you have any ideas on why it runs out of memory? Can anything be done about that?

Thank you!

Partial stacktrace before the crash:
```stacktrace
05-05 17:06:57.487 22522-22619/com.app E/unknown:React: Exception in native call
                                                             java.lang.RuntimeException: Could not invoke RNFetchBlob.fetchBlob
                                                                 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:382)
                                                                 at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
                                                                 at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138) 
                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                 at android.os.Handler.handleCallback(Handler.java:739) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208) 
                                                                 at java.lang.Thread.run(Thread.java:818) 
                                                              Caused by: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
                                                                 at java.lang.Thread.nativeCreate(Native Method)
                                                                 at java.lang.Thread.start(Thread.java:1063)
                                                                 at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
                                                                 at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                 at okhttp3.Dispatcher.enqueue(Dispatcher.java:129)
                                                                 at okhttp3.RealCall.enqueue(RealCall.java:78)
                                                                 at com.RNFetchBlob.RNFetchBlobReq.run(RNFetchBlobReq.java:372)
                                                                 at com.RNFetchBlob.RNFetchBlob.fetchBlob(RNFetchBlob.java:317)
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368) 
                                                                 at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138) 
                                                                 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                 at android.os.Handler.handleCallback(Handler.java:739) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                 at android.os.Looper.loop(Looper.java:148) 
                                                                 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208) 
                                                                 at java.lang.Thread.run(Thread.java:818) 
```

**Comment by kfiroo** [comment]
Hey @sladkoff 
Currently we start a prefetch task for each url concurrently and let the underlying native code handle the workload, I think what's happening is that you are overloading it with requests and it runs out of memory.

You could implement you own `ImageCacheProvider` to handle this, or you could try calling `cacheMultipleImages` with smaller batches

**Comment by kfiroo** [comment]
Also, we are saving all images to `RNFetchBlob.fs.dirs.CacheDir` see [docs](https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#dirs)
I'm not sure if this space is limited.

**Comment by sladkoff** [comment]
Hey @kfiroo 
Thanks for the quick answer. 
I'm now batching the requests and it works perfectly.

I read up on the Android cache dir. 
It doesn't seem to have limited space but it's still unrecommended to store lots of data.

> You should always maintain the cache files yourself and stay within a reasonable limit of space consumed, such as 1MB. When the user uninstalls your application, these files are removed.

**Comment by sladkoff** [comment]
Also here's how I batched my image requests in case anyone needs this:

```js
import {Promise as Bluebird} from 'bluebird'

function downloadImages(imageUrls) { 
    var chunks = [];
    var chunkSize = 10;
    // split large array of image urls into chunks
    for (var i = 0, j = imageUrls.length; i < j; i += chunkSize) {
        chunks.push(imageUrls.slice(i, i + chunkSize));
     }

    // I used the Bluebird Promise library to wait for each batch of requests to finish before starting another
    return Bluebird.each(chunks, (chunk) => {
        return ImageCacheProvider.cacheMultipleImages(chunk);
    })
}
```

**Comment by naytun** [comment]
Try this one!! It works with expo@v25 and I’m using it in my project.

https://hackernoon.com/smart-images-in-react-native-db0ef047dd8c
